### ISSUE TITLE
unexpected type 'int' 

### ISSUE THREAD

**Issue by bonometti** [gtergeomatica/cdu_creator#4]
TypeError: QgsVectorLayer.selectByExpression(): argument 2 has unexpected type 'int' 
Traceback (most recent call last):
  File "C:\Users/xxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cdu_creator-master\cdu_creator.py", line 601, in addMapButton
    self.lyr.selectByExpression("{}='{}' AND {}='{}'".format(self.fog_list[0].casefold(), sel_foglio, self.map_list[0].casefold(), sel_particella), 1)
TypeError: QgsVectorLayer.selectByExpression(): argument 2 has unexpected type 'int'

**Comment by RobiFag** [comment]
La problematica così segnalata non è di facile comprensione, se potesse specificare meglio il problema oltre a riportare l'errore che le restituisce QGIS, sarebbe più gfacile per noi capire il problema e fornirle la possibile soluzione.

Dall'errore comunque potrebbe essere dovuto alla tipologia delle colonne in cui è specificata la sezione, il foglio e il mappale. Una o tutte queste colonne sono di tipo numerico mentre dovrebbero essere di tipo stringa come indicato nel manuale del plugin.
